AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  uploader

Parameters:
  DomainName:
    Type: String
  Certificate:
    Type: String
  UserPoolId:
    Type: String
  CallbackURL:
    Type: String
  LogoutURL:
    Type: String
  UserNameIndex:
    Type: String
    Default: NameIndex
  FileUserIndex:
    Type: String
    Default: UserIndex
  CloudFrontManagedCachePolicy:
    Type: String
    Default: "658327ea-f89d-4fab-a63d-7e88639e58f6"
  FilePublicKeySSMName:
    Type: String
  FilePrivateKeySecretsArn:
    Type: String

Globals:
  Function:
    Runtime: provided.al2023
    Handler: bootstrap
    Architectures:
      - x86_64

Resources:
  UserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      UserPoolId: !Ref UserPoolId
      SupportedIdentityProviders:
        - COGNITO
      GenerateSecret: false
      CallbackURLs:
        - !Ref CallbackURL
      LogoutURLs:
        - !Ref LogoutURL
      AllowedOAuthFlowsUserPoolClient: true
      AllowedOAuthFlows:
        - code
      AllowedOAuthScopes:
        - email
        - openid
      ExplicitAuthFlows:
        - ALLOW_USER_PASSWORD_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
      IdTokenValidity: 1
      AccessTokenValidity: 1
      RefreshTokenValidity: 30
      TokenValidityUnits:
        IdToken: "hours"
        AccessToken: "hours"
        RefreshToken: "days"

  UserTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: Id
          AttributeType: S
        - AttributeName: Attr
          AttributeType: S
        - AttributeName: Name
          AttributeType: S
      KeySchema:
        - AttributeName: Id
          KeyType: HASH
        - AttributeName: Attr
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: !Ref UserNameIndex
          KeySchema:
            - AttributeName: Name
              KeyType: HASH
          Projection:
            ProjectionType: KEYS_ONLY

  FileTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: Key
          AttributeType: S
        - AttributeName: Attr
          AttributeType: S
        - AttributeName: UserIdx
          AttributeType: S
        - AttributeName: TS
          AttributeType: N
      KeySchema:
        - AttributeName: Key
          KeyType: HASH
        - AttributeName: Attr
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: !Ref FileUserIndex
          KeySchema:
            - AttributeName: UserIdx
              KeyType: HASH
            - AttributeName: TS
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      StreamSpecification:
        StreamViewType: NEW_IMAGE

  FileBucket:
    Type: AWS::S3::Bucket
    Properties:
      PublicAccessBlockConfiguration:
        BlockPublicPolicy: false

  FileBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref FileBucket
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: cloudfront.amazonaws.com
            Action:
              - s3:ListBucket
              - s3:GetObject
            Resource:
              - !Sub "arn:aws:s3:::${FileBucket}/*"
              - !Sub "arn:aws:s3:::${FileBucket}"
            Condition:
              StringEquals:
                AWS:SourceArn: !Sub "arn:aws:cloudfront::${AWS::AccountId}:distribution/${ConsoleDistribution}"

  ConsoleBucket:
    Type: AWS::S3::Bucket
    Properties:
      PublicAccessBlockConfiguration:
        BlockPublicPolicy: false

  ConsoleBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref ConsoleBucket
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: cloudfront.amazonaws.com
            Action:
              - s3:ListBucket
              - s3:GetObject
            Resource:
              - !Sub "arn:aws:s3:::${ConsoleBucket}/*"
              - !Sub "arn:aws:s3:::${ConsoleBucket}"
            Condition:
              StringEquals:
                AWS:SourceArn: !Sub "arn:aws:cloudfront::${AWS::AccountId}:distribution/${ConsoleDistribution}"

  Api:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: prod
      CorsConfiguration:
        AllowHeaders:
          - Content-Type
          - Authorization
        AllowMethods:
          - POST
          - GET
          - PUT
          - DELETE
          - OPTIONS
        AllowOrigins:
          - '*'
      Auth:
        Authorizers:
          OAuth2Authorizer:
            IdentitySource: '$request.header.Authorization'
            JwtConfiguration:
              audience:
                - !Ref UserPoolClient
              issuer: !Sub "https://cognito-idp.${AWS::Region}.amazonaws.com/${UserPoolId}"
        DefaultAuthorizer: OAuth2Authorizer

  ConsoleFileOAC:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Name: !Sub "${AWS::StackName}-Console"
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4

  ConsoleApiCachePolicy:
    Type: AWS::CloudFront::CachePolicy
    Properties:
      CachePolicyConfig:
        Name: !Sub "${AWS::StackName}-ConsoleApiCachePolicy"
        DefaultTTL: 3600
        MaxTTL: 3600
        MinTTL: 1
        ParametersInCacheKeyAndForwardedToOrigin:
          CookiesConfig:
            CookieBehavior: none
          HeadersConfig:
            HeaderBehavior: whitelist
            Headers:
              - Authorization
          QueryStringsConfig:
            QueryStringBehavior: all
          EnableAcceptEncodingBrotli: True
          EnableAcceptEncodingGzip: True

  FilePublicKey:
    Type: AWS::CloudFront::PublicKey
    Properties:
      PublicKeyConfig:
        Name: !Sub "file-publickey-${AWS::StackName}"
        CallerReference: !Sub "${AWS::StackName}-pubkey"
        EncodedKey: !Sub "{{resolve:ssm:${FilePublicKeySSMName}}}"

  FileKeyGroup:
    Type: AWS::CloudFront::KeyGroup
    Properties:
      KeyGroupConfig:
        Name: !Sub "file-keygroup-${AWS::StackName}"
        Items:
          - !Ref FilePublicKey

  ConsoleDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        DefaultRootObject: index.html
        PriceClass: PriceClass_200
        Aliases:
          - !Ref DomainName
        ViewerCertificate:
          AcmCertificateArn: !Ref Certificate
          MinimumProtocolVersion: TLSv1.2_2021
          SslSupportMethod: sni-only
        Origins:
          - Id: !Sub "s3-${ConsoleBucket}"
            DomainName: !GetAtt ConsoleBucket.RegionalDomainName
            OriginAccessControlId: !GetAtt ConsoleFileOAC.Id
            S3OriginConfig: {}
          - Id: !Sub "s3-${FileBucket}"
            DomainName: !GetAtt FileBucket.RegionalDomainName
            OriginAccessControlId: !GetAtt ConsoleFileOAC.Id
            S3OriginConfig: {}
          - Id: !Sub "api-${Api}"
            DomainName: !Sub "${Api}.execute-api.${AWS::Region}.amazonaws.com"
            OriginPath: !Sub "/${ApiprodStage}"
            CustomOriginConfig:
              HTTPSPort: 443
              OriginProtocolPolicy: https-only
              OriginSSLProtocols:
                - TLSv1.2
              OriginReadTimeout: 30
              OriginKeepaliveTimeout: 5
        CacheBehaviors:
          - TargetOriginId: !Sub "api-${Api}"
            CachePolicyId: !Ref ConsoleApiCachePolicy
            PathPattern: /v1/*
            ViewerProtocolPolicy: https-only
            AllowedMethods:
              - GET
              - HEAD
              - DELETE
              - OPTIONS
              - PATCH
              - POST
              - PUT
          - TargetOriginId: !Sub "s3-${FileBucket}"
            CachePolicyId: !Ref CloudFrontManagedCachePolicy
            PathPattern: /files/*
            ViewerProtocolPolicy: https-only
            AllowedMethods:
              - GET
              - HEAD
            TrustedKeyGroups:
              - !Ref FileKeyGroup
        DefaultCacheBehavior:
          CachePolicyId: !Ref CloudFrontManagedCachePolicy
          TargetOriginId: !Sub "s3-${ConsoleBucket}"
          ViewerProtocolPolicy: https-only
          AllowedMethods:
            - GET
            - HEAD
        CustomErrorResponses:
          - ErrorCode: 404
            ResponseCode: 200
            ResponsePagePath: /index.html

  UserFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: api/user/
      Environment:
        Variables:
          REGION: !Ref AWS::Region
          USER_TABLE: !Ref UserTable
          USER_NAME_INDEX: !Ref UserNameIndex
      Events:
        Get:
          Type: HttpApi
          Properties:
            ApiId: !Ref Api
            Method: GET
            Path: /v1/user/{userId}

  UserFunctionPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: UserFunctionPolicy
      Roles:
        - !Ref UserFunctionRole
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - dynamodb:GetItem
              - dynamodb:BatchGetItem
              - dynamodb:PutItem
              - dynamodb:Query
              - dynamodb:TransactWriteItems
            Resource:
              - !GetAtt UserTable.Arn
              - !Sub
                - "${TableArn}/index/*"
                - TableArn: !GetAtt UserTable.Arn

  FileFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: api/file/
      Environment:
        Variables:
          REGION: !Ref AWS::Region
          USER_TABLE: !Ref UserTable
          USER_NAME_INDEX: !Ref UserNameIndex
          FILE_TABLE: !Ref FileTable
          FILE_USER_INDEX: !Ref FileUserIndex
          FILE_BUCKET: !Ref FileBucket
          FILE_PRIVATE_KEY_SECRET_NAME: !Ref FilePrivateKeySecretsArn
          KEY_PAIR_ID: !Ref FilePublicKey
          DOMAIN_NAME: !Ref DomainName
          FILE_PREFIX: /files
      Events:
        Upload:
          Type: HttpApi
          Properties:
            ApiId: !Ref Api
            Method: POST
            Path: /v1/file
        List:
          Type: HttpApi
          Properties:
            ApiId: !Ref Api
            Method: GET
            Path: /v1/file
        Get:
          Type: HttpApi
          Properties:
            ApiId: !Ref Api
            Method: GET
            Path: /v1/file/{key}
        Update:
          Type: HttpApi
          Properties:
            ApiId: !Ref Api
            Method: PUT
            Path: /v1/file/{key}
        Delete:
          Type: HttpApi
          Properties:
            ApiId: !Ref Api
            Method: DELETE
            Path: /v1/file/{key}

  FileFunctionPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: FileFunctionPolicy
      Roles:
        - !Ref FileFunctionRole
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - dynamodb:GetItem
              - dynamodb:BatchGetItem
              - dynamodb:Query
            Resource:
              - !GetAtt UserTable.Arn
              - !Sub
                - "${TableArn}/index/*"
                - TableArn: !GetAtt UserTable.Arn
          - Effect: Allow
            Action:
              - dynamodb:Query
              - dynamodb:PutItem
              - dynamodb:UpdateItem
              - dynamodb:TransactWriteItems
            Resource:
              - !GetAtt FileTable.Arn
              - !Sub
                - "${TableArn}/index/*"
                - TableArn: !GetAtt FileTable.Arn
          - Effect: Allow
            Action:
              - s3:ListBucket
            Resource:
              - !GetAtt FileBucket.Arn
          - Effect: Allow
            Action:
              - s3:PutObject
              - s3:GetObject
              - s3:DeleteObject
            Resource:
              - !Sub
                - "${BucketArn}/*"
                - BucketArn: !GetAtt FileBucket.Arn
          - Effect: Allow
            Action:
              - cloudfront:CreateInvalidation
            Resource:
              - !Sub "arn:aws:cloudfront::${AWS::AccountId}:distribution/${ConsoleDistribution}"
          - Effect: Allow
            Action:
              - secretsmanager:GetSecretValue
            Resource:
              - !Ref FilePrivateKeySecretsArn

  ImageFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: lambda/image/
      Environment:
        Variables:
          REGION: !Ref AWS::Region
          FILE_TABLE: !Ref FileTable
          FILE_USER_INDEX: !Ref FileUserIndex
          DISTRIBUTION: !Ref ConsoleDistribution
      Events:
        DBStream:
          Type: DynamoDB
          Properties:
            Stream: !GetAtt FileTable.StreamArn
            StartingPosition: LATEST
            FilterCriteria:
              Filters:
                - Pattern: '{"eventName":["UPDATE"],"dynamodb":{"Keys":{"Attr":{"S":["orig"]}}}}'

  ImageFunctionPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: ImageFunctionPolicy
      Roles:
        - !Ref ImageFunctionRole
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - dynamodb:Query
              - dynamodb:PutItem
              - dynamodb:UpdateItem
              - dynamodb:DeleteItem
              - dynamodb:TransactWriteItems
            Resource:
              - !GetAtt FileTable.Arn
              - !Sub
                - "${TableArn}/index/*"
                - TableArn: !GetAtt FileTable.Arn
          - Effect: Allow
            Action:
              - s3:PutObject
              - s3:GetObject
              - s3:DeleteObject
            Resource:
              - !Sub
                - "${BucketArn}/*"
                - BucketArn: !GetAtt FileBucket.Arn
          - Effect: Allow
            Action:
              - cloudfront:CreateInvalidation
            Resource:
              - !Sub "arn:aws:cloudfront::${AWS::AccountId}:distribution/${ConsoleDistribution}"

Outputs:
  UserPoolClientId:
    Value: !Ref UserPoolClient
  ConsoleBucket:
    Value: !Ref ConsoleBucket
  ConsoleDistribution:
    Value: !Ref ConsoleDistribution
  ConsoleDistributionDomainName:
    Value: !GetAtt ConsoleDistribution.DomainName
